<?php
// Auto-generated by build-components.js — DO NOT EDIT
$active_components = ["sticky","utility","grid","nav","navbar","icon","slidenav","modal","close","accordion","tabs","switcher","offcanvas","drop","dropbar","dropnav","dropdown","tooltip","notification","pagination","dotnav","slideshow","slider","lightbox","animation","visibility","width","height","position","cover","parallax","scrollspy","transition","spinner","inverse","svg","video","iframe"];
